
# List of resource files that kustomize reads, modifies
# and emits as a YAML string
resources:
- ../../../base/web

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: quay.io/bclaster/roar-web
  newTag: 1.0.56
