
# List of resource files that kustomize reads, modifies
# and emits as a YAML string
resources:
- ../../../base/db

# Change the image name and version
images:
- name: quay.io/bclaster/roar-db
  newTag: 0.0.56
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
